services:
  ho_emulator:
    image: ghcr.io/qznwpfqbgw/ho_emu_server:quic
    volumes:
      - ./src:/app/ho_emulator
      - /dev/pts:/dev/pts
      - /home/wmnlab/Desktop/experiment_log:/home/wmnlab/Desktop/experiment_log
      - /home/wmnlab/Data:/home/wmnlab/Data
      - /home/wmnlab/temp: /home/wmnlab/temp
    privileged: true
    command: /bin/bash
    stdin_open: true