Global:
  # One of mi2log and xml_log should be provided
  # mi2lg should be provided if Controller.enable is True
  mi2log: ./test/diag_log_sm00_2024-10-11_16-13-35.mi2log
  xml_log: ./test/diag_log_sm00_2024-10-11_16-13-35.xml

  # optional
  db_log: ./test/diag_log_sm00_2024-10-11_16-13-35.db

Controller:
  enable: True
  parameters_file: test/br_dl_test_event_params.csv
  inrerface: eth0
  perfect_stable: True

Replayer:
  enable: False
  virt_serial_port: /tmp/ttyV0